# version: "3.8"

services:
  # Reuse the existing nginx-proxy from igraphical setup
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    environment:
      CLIENT_MAX_BODY_SIZE: 10m
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
    networks:
      - app_network

  # Reuse the existing nginx-letsencrypt container
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
    networks:
      - app_network

  #! Database service
  database:
    image: mysql:8.0.32
    container_name: ezlegin-database
    platform: linux/amd64
    restart: always
    environment:
      DATABASE_URL: mysql://root:R@MIN3517r@m@localhost:3306/ezlegin
      MYSQL_DATABASE: ezlegin
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - ezlegin_database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app_network

  #! Tutor service
  tutor:
    build:
      context: .
      dockerfile: ./apps/tutor/Dockerfile
      extra_hosts:
        - "binaries.prisma.sh:125.125.125.125" # IRAN sanctions workaround
        - "registry.npmjs.org:125.125.125.125" # IRAN sanctions workaround
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        RESEND_API_KEY: ${RESEND_API_KEY}
    container_name: ezlegin-tutor
    restart: always
    env_file:
      - /root/projects/ezlegin/apps/tutor/.env.local
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: tutor.ezlegin.com
      LETSENCRYPT_HOST: tutor.ezlegin.com
      LETSENCRYPT_EMAIL: admin@ezlegin.com
      DATABASE_URL: "mysql://root@ezlegin-database:3306/ezlegin"
      NEXTAUTH_URL: https://tutor.ezlegin.com
      CLIENT_MAX_BODY_SIZE: 10m
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ezlegin_db_backups:/app/backups

  #! Admin service
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      extra_hosts:
        - "binaries.prisma.sh:125.125.125.125" # IRAN sanctions workaround
        - "registry.npmjs.org:125.125.125.125" # IRAN sanctions workaround
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        RESEND_API_KEY: ${RESEND_API_KEY}
    container_name: ezlegin-admin
    restart: always
    env_file:
      - /root/projects/ezlegin/apps/admin/.env.local
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: admin.ezlegin.com
      LETSENCRYPT_HOST: admin.ezlegin.com
      LETSENCRYPT_EMAIL: admin@ezlegin.com
      NEXTAUTH_URL: https://admin.ezlegin.com
      CLIENT_MAX_BODY_SIZE: 10m
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ezlegin_db_backups:/app/backups
      - /root/projects/ezlegin/apps/admin/ga.json:/app/ga.json:ro # Google Analytics

  #! App service
  app:
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
      extra_hosts:
        - "binaries.prisma.sh:125.125.125.125" # IRAN sanctions workaround
        - "registry.npmjs.org:125.125.125.125" # IRAN sanctions workaround
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        RESEND_API_KEY: ${RESEND_API_KEY}
    container_name: ezlegin-app
    restart: always
    env_file:
      - /root/projects/ezlegin/apps/app/.env.local
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ezlegin.com
      LETSENCRYPT_HOST: ezlegin.com
      LETSENCRYPT_EMAIL: admin@ezlegin.com
      NEXTAUTH_URL: https://ezlegin.com
      CLIENT_MAX_BODY_SIZE: 10m
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ezlegin_db_backups:/app/backups

volumes:
  ezlegin_database:
  ezlegin_certs:
  ezlegin_vhost.d:
  ezlegin_html:
  ezlegin_db_backups:

networks:
  app_network:
    external: true
